rvm:
- 2.0.0

before_install:
- 'echo ''gem: --no-document'' > ~/.gemrc'
- gem install bundler --pre
- echo '--colour' > ~/.rspec
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
- cp sample.env .env
- psql -c 'create database "sched-do_test";' -U postgres
- bundle exec rake db:migrate db:test:prepare

bundler_args: -j8 --without development staging production --path=~/.bundle

script:
- bundle exec rake spec
- bundle exec rake guard:jasmine

env:
  global:
  - RAILS_ENV=test
